services:
  postgres:
    image: postgres:15
    container_name: next-todo-postgres
    ports:
      - '54321:5432' # 使用你配置的端口
    volumes:
      - ./backend/postgres.conf:/etc/postgresql/postgresql.conf:ro
    tmpfs:
      - /var/lib/postgresql/data
      - /tmp
    environment:
      POSTGRES_DB: next_todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf

  electric:
    image: electricsql/electric
    container_name: next-todo-electric
    ports:
      # ElectricSQL runs on port 3000 inside the container
      - 5133:3000
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/next_todo?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
      # Performance optimizations
      ELECTRIC_DEBUG: true
      ELECTRIC_USAGE_REPORTING: false
      # Additional performance settings
      ELECTRIC_LOG_LEVEL: debug
      ELECTRIC_MAX_CONNECTIONS: 10
      ELECTRIC_POOL_SIZE: 5
      # Timeout and performance settings
      ELECTRIC_SYNC_TIMEOUT: 5000
      ELECTRIC_WAL_TIMEOUT: 3000
    depends_on:
      - postgres